version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payment
      MYSQL_USER: payment
      MYSQL_PASSWORD: payment
    ports:
      - "3306:3306"

  payment-api:
    build:
      context: ./payment-api
    container_name: payment-api
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: payment
      MYSQL_USER: payment
      MYSQL_PASSWORD: payment
      DEEPSHIELD_DEMO_MODE: "true"
    ports:
      - "8000:8000"
